#cloud-config
hostname: debian-host
manage_etc_hosts: true

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

timezone: Europe/Kyiv

chpasswd:
  expire: false
  users:
  - {name: root, password: password, type: text}

runcmd:
  - sed -i 's/[#]*PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  - systemctl reload ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent